### ISSUE TITLE
Scroll bars visible in Chrome 49

### ISSUE THREAD

**Issue by ablakey** [thejameskyle/spectacle-code-slide#1]
See attached. This happens when I run your demo page.   

Confirmed I'm at 100% zoom level.

Let me know what other data you might want to help address this issue.

http://imgur.com/nuGdpm9

**Comment by thejameskyle** [comment]
Hm... I could make [this](https://github.com/thejameskyle/spectacle-code-slide/blob/master/src/CodeSlide.js#L35) `overflow: hidden` and rely solely on the keyboard navigation, but that prevents horizontal scrolling which you'd want.

That'd be easy to solve with `overflow-x: auto;` so you only see the horizontal scrollbar here.

I'll see how my first talk using this goes and report back.

**Comment by ablakey** [comment]
I would only want to use up or down arrows to move through my "slides".  If scrolling is needed, I should either fix my code to not have such long lines, or adjust the font size. But I would ideally want there to be no unnecessary elements on the page when I'm talking code.

Maybe it should just be a configuration option.

**Comment by thejameskyle** [comment]
I've fixed this, code now wraps onto a new line, which looks ugly but you should probably limit yourself to short lines anyways

**Comment by atuttle** [comment]
Perhaps related; is there any way to specify that the code container should be 100% width? I can see how you might not want it if your code sample has very short lines, but if you know you've got longer lines, why not take advantage of all available space via an opt-in attribute?

**Comment by thejameskyle** [comment]
I have no idea how to do that. @kenwheeler ?

**Comment by kenwheeler** [comment]
You can use a `maxWidth` prop to make your content area larger

**Comment by atuttle** [comment]
:ok_hand: awesome, thanks!
