### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by candidodmv** [thejameskyle/spectacle-code-slide#11]
I don't find specification for usage with other contexts only with React, is it possible to use this library with other languages?

**Comment by thejameskyle** [comment]
I'm not sure what you mean by other languages

**Comment by iissnan** [comment]
Could it be possible to use with AngularJS? 

Thanks

**Comment by thejameskyle** [comment]
no

**Comment by candidodmv** [comment]
My question was about the usage with other languages, that implements syntax  highlighter. Is it possible? For example, I want use with c/c++ your tool will  recognize this language the syntax highlighter? Thanks

**Comment by thejameskyle** [comment]
It supports anything that http://prismjs.com/ supports

**Comment by candidodmv** [comment]
That's fine! Thanks!
