### ISSUE TITLE
Prism.js error - Cannot read property 'rest' of undefined

### ISSUE THREAD

**Issue by hhsnopek** [thejameskyle/spectacle-code-slide#14]
I keep getting an error with `Prism.js`, a second set of eyes might be able to see my problem?
error: `prism.js:242Uncaught TypeError: Cannot read property 'rest' of undefined`

```js
		  <CodeSlide lang="go"
		  transition={["fade"]}
		  code={require("raw!../assets/permissions.go")}
		  ranges={[
			  { loc: [0, 1], title: "Permissions ..." },
			  { loc: [0, 28], title: "Auth" }
		  ]}/>
```

**Comment by hhsnopek** [comment]
self solved true trial and error
I was loading the incorrect language package for prism, creating a PR that adds clarity to the readmin

**Comment by IdahoEv** [comment]
Argh, how did you solve this @hhsnopek ?  Cannot find your PR, cannot find any information on "language packages for prism" either here or at the prism.js site.

**Comment by hhsnopek** [comment]
@IdahoEv tbh I don't quite remember... but here's a link to the updated [snippet](https://github.com/hhsnopek/capstone-presentation/blob/master/presentation/index.js#L94)

**Comment by cramirez451** [comment]
@IdahoEv additional prism languages have to be loaded separately. For example if you're using node and you want to highlight your code with http you can do the following:

var Prism = require('prismjs')
require('prismjs/components/prism-http')

var code = "this string should be highlighted with http"
Prism.highlight(code, Prism.languages.http);

**Comment by k-funk** [comment]
Seems like this should be in the Usage docs.
