### ISSUE TITLE
Can't get HTML code to display properly

### ISSUE THREAD

**Issue by atuttle** [thejameskyle/spectacle-code-slide#16]
I'm using version 0.1.8 as suggested in #10 because I couldn't get it to run otherwise.

At first I tried requiring the html file:

```js
          <CodeSlide
            lang="html"
            transition={["zoom"]}
            code={require('raw!../assets/code-1-start.html')}
            ranges={[
              { loc: [0,1] }
            ]}
          />
```

Which threw the error:

> ERROR in ./~/raw-loader!./assets/code-1-start.html
> Module parse failed: [...]/deck/node_modules/raw-loader/index.js![...]/deck/assets/code-1-start.html Line 1: Unexpected token ILLEGAL
> You may need an appropriate loader to handle this file type.
> | module.exports = `"<html> \n\t<div id=\"app\"></div>\n </html>\n"`
> @ ./presentation/index.js 316:18-60

So then I tried inlining the HTML:

```js
          <CodeSlide
            lang="html"
            transition={["zoom"]}
            code="<html> 
  <div id='app'></div>
 </html>"
            ranges={[
              { loc: [0,1] }
            ]}
          />
```

Which does display my code, but not with the linebreaks. I tried both indenting with tabs and with spaces, both options look like this:

![image](https://cloud.githubusercontent.com/assets/46990/15094417/4eae0de2-1471-11e6-9714-4175d5fb2d26.png)

I've found that if I remove the indentation, it will use the correct linebreaks, but obviously indentation is helpful to have...

![image](https://cloud.githubusercontent.com/assets/46990/15094421/b1415c16-1471-11e6-89a9-301d6f6a1617.png)

I also tried manually adding \n\t where appropriate, but that's not the solution either:

![image](https://cloud.githubusercontent.com/assets/46990/15094450/8f639f90-1472-11e6-92ef-fcbd9c12464e.png)

Any ideas?

**Comment by thejameskyle** [comment]
Both work fine:

- https://github.com/hzoo/react-pres/blob/master/presentation/index.js#L252
- https://github.com/hzoo/react-pres/blob/master/presentation/index.js#L360-L364

You must have something setup wrong

**Comment by atuttle** [comment]
I started with [spectacle-boilerplate](https://github.com/FormidableLabs/spectacle-boilerplate/), which seems to be an issue common to people that were affected on #10, too. Its readme directs you to clone the repo, run `npm install`, and then `rm -R .git` to detach from their repo, which is what I did.

If not that, is there some other advice for initial content with Spectacle, since they recommend their boilerplate?

```
$ npm ls --depth=0
spectacle-boilerplate@1.0.1
├── autoprefixer-core@6.0.1
├── babel-core@6.7.4
├── babel-eslint@5.0.1
├── babel-loader@6.2.4
├── babel-polyfill@6.7.4
├── babel-preset-es2015@6.6.0
├── babel-preset-react@6.5.0
├── babel-preset-react-hmre@1.1.1
├── babel-preset-stage-0@6.5.0
├── css-loader@0.23.1
├── eslint@1.10.3
├── eslint-config-defaults@7.1.1
├── eslint-plugin-filenames@0.1.2
├── eslint-plugin-react@3.16.1
├── express@4.13.4
├── file-loader@0.8.5
├── html-loader@0.4.3
├── is-buffer@1.1.3
├── markdown-loader@0.1.7
├── node-libs-browser@0.5.3
├── normalize.css@3.0.3
├── raw-loader@0.5.1
├── react@0.14.8
├── react-dom@0.14.7
├── rimraf@2.5.2
├── spectacle@1.0.6
├── spectacle-code-slide@0.1.8
├── style-loader@0.13.1
├── surge@0.17.7
├── url-loader@0.5.7
├── webpack@1.12.14
├── webpack-dev-middleware@1.6.1
└── webpack-hot-middleware@2.10.0
```

I'm running everything by running `npm start` which uses webpack

**Comment by atuttle** [comment]
After upgrading to the latest node, I was getting different errors, but still unable to figure out what they meant. Based on the errors coming out of Webpack:

```
ERROR in ./index.js
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at [...]/deck/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
    at [...]/deck/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
    at Array.map (native)
    at OptionManager.resolvePresets ([...]/deck/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets ([...]/deck/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions ([...]/deck/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at [...]/deck/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
    at [...]/deck/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
```

I decided to try upgrading all of the babel things.

![13x2yf](https://cloud.githubusercontent.com/assets/46990/15160608/7acbb9b6-16c8-11e6-96f3-6e86b967f0f3.jpg)

Looking up the latest released version for each babel-related package in my package.json, I updated them accordingly:

    "babel-core": "^6.8.0",
    "babel-eslint": "^5.0.0-beta6",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "^6.8.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-stage-0": "^6.5.0",

Then after an npm install I was back on my feet. I hope this helps someone else dealing with similar issues down the line!

I think what bit me the worst throughout this was my unfamiliarity with Webpack. I was mistaking webpack build errors for runtime errors and that led me to some false conclusions.
