### ISSUE TITLE
Presenter view support?

### ISSUE THREAD

**Issue by TheEvilDev** [thejameskyle/spectacle-code-slide#3]
Playing with the library, I noticed the transitions do not seem to work from the presenter view. Is there support for this yet, or is my code likely just broken?

The behavior I'm seeing, is using the keyboard shortcuts on the presenter site (http://localhost:3000?presenter) I see the actions occur in the presenter view, but they are not reflected on the normal view when navigating with keyboard shortcuts.

**Comment by thejameskyle** [comment]
Done

**Comment by TheEvilDev** [comment]
Works great, thanks!
