### ISSUE TITLE
How to correctly install spectacle-code-slide

### ISSUE THREAD

**Issue by skjorrface** [thejameskyle/spectacle-code-slide#8]
I tried installing spectacle-code-slide along with the spectacle-boilerprate: I clone the spectacle boilerplate first, then I type: npm i && npm i spectacle-code-slide --save. Then I modify presentation/index.js with your code (I define the theme, transition etc.), and put code.example into assets/.

When I run npm run start and go to http://localhost:3000/ the slides are just "stuck" and don't move with the arrows, but if I go to http://localhost:3000/0 it correctly works. I get a console error at http://localhost:3000 :

"Uncaught TypeError: Cannot read property 'scrollTop' of undefined"

What am I doing wrong?

**Comment by thejameskyle** [comment]
uhh, what does your CodeSlide declaration look like?

**Comment by skjorrface** [comment]
`import React from "react";  
import { Deck, Spectacle } from "spectacle";  
import createTheme from "spectacle/lib/themes/default";  
import CodeSlide from "spectacle-code-slide";

const theme = createTheme({  
  primary: "#ffffff"
});

export default class Presentation extends React.Component {  
  render() {
    return (
      <Spectacle theme={theme}>
  <Deck transition={["slide"]} transitionDuration={0} progress="bar">
    <CodeSlide
      transition={["slide"]}
      lang="html"
      code={require("raw!../assets/code.example")}
      ranges={[
        { loc: [0, 1],
          title: "Learn HTML 5",
          note: "Use arrow keys to navigate through the slides!" },

        { loc: [0, 1],
          title: "Learn HTML 5",
          note: "First line defines document type for HTML5" },

        { loc: [1, 2],
          note: "This is the main tag, any other HTML code is inside here" },

        { loc: [2, 6],
          note: "The <head> tag contains \"meta information\" and other useful tags which don't display directly on the page etc."},

        { loc: [6, 12],
          note: "The <body> tag is where we put anything we want to see in our page:"},

        { loc: [7, 11],
          note: "A <div> tag to enclose sections inside our page"},

        { loc: [8, 9],
          note: "A <h2> heading tag to define our page title"},

        { loc: [9, 10],
          note: "A <p> paragraph to enclose our page actual text contents."},

        { loc: [13, 14], note: "</html> is the definitive closing tag, it ensures we're done writing HTML in this file."},
        { loc: [13, 16], title: "Thank you!"}
      ]}
    />
  </Deck>
</Spectacle>  
  );
  }
}`

This is presentation/index.js

`<!DOCTYPE html>  
<html>  
  <head>
    <meta charset="UTF-8">
    <title>My first HTML page</title>
  </head>
  <body>
    <div id="main">
      <h2>My HTML page title</h2>
      <p>My HTML page content</h1>
    </div>
  </body>
</html>`

and this is code.example inside assets/

**Comment by thejameskyle** [comment]
Can you see if something is erroring with this line? https://github.com/thejameskyle/spectacle-code-slide/blob/master/src/CodeSlide.js#L108

**Comment by skjorrface** [comment]
hrm I'm not sure, console error yields:

scrollToElement.js:11 Uncaught TypeError: Cannot read property 'scrollTop' of undefined

**Comment by Sekhmet** [comment]
This is the same error that #10. Problem is that container is undefined at time of initial scrolling. I will try to investigate it more tomorrow.

**Comment by thejameskyle** [comment]
Moving to #10 since it details the issue more
